<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>627e98b4-b700-4c56-91ec-e2949fa29ba5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CRGorman.Demo.ApiService\CRGorman.Demo.ApiService.csproj" />
    <ProjectReference Include="..\CRGorman.Demo.MigrationService\CRGorman.Demo.MigrationService.csproj" />
    <ProjectReference Include="..\CRGorman.Demo.SpeedrunData\CRGorman.Demo.SpeedrunData.csproj" />
    <ProjectReference Include="..\CRGorman.Demo.Web\CRGorman.Demo.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.0" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="9.3.0" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="9.3.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
  </ItemGroup>

</Project>
